name: PW Tests

run-name: ${{ github.actor }} is running autotests 🚀

on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Load environment variables
        run: |
          echo "Loading environment variables from .env file"
          npm install dotenv
          node -e "require('dotenv').config()"
      - run: npx playwright test --list
      - run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
