name: PW Tests

run-name: ${{ github.actor }} is running autotests 🚀

on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Load .env file
        uses: fnkr/github-actions-set-env@v2
        with:
          envFilePath: .env
      - name: Print environment variables
        run: |
          echo $LOGIN
          echo $PASSWORD
      - run: npx playwright test
      - name: Display logs
        run: cat playwright-report/test-results.log || true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
